# -------------------------------------------------------------------------------
# Copyright:   (c) BLS OPS LLC.
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
# -------------------------------------------------------------------------------
# verse_of_the_day.py

import random
import re

verse_mapping = {
	# Books
	## Old Testament
	"Genesis":"Turing",
	"GENESIS":"Turing",
	"Exodus":"Sandbox Escape",
	"EXODUS":"Sandbox Escape",
	"Leviticus":"Applications",
	"LEVITICUS":"Applications",
	"Numbers":"Computations",
	"NUMBERS":"Computations",
	"Deuteronomy":"Cryptography",
	"DEUTERONOMY":"Cryptography",
	"Joshua":"Worm",
	"JOSHUA":"Worm",
	"Judges":"NT Authority\\SYSTEM",
	"JUDGES":"NT Authority\\SYSTEM",
	"Ruth":"RAT",
	"RUTH":"RAT",
	"First Samuel":"Python2",
	"FIRST SAMUEL":"Python2",
	"Second Samuel":"Python3",
	"SECOND SAMUEL":"Python3",
	"First Kings":"First Administrators",
	"FIRST KINGS":"First Administrators",
	"Second Kings":"Second Administrators",
	"SECOND KINGS":"Second Administrators",
	"Job":"CronJob",
	"JOB":"CronJob",
	"First Chronicles":"First CronJobicles",
	"FIRST CHRONICLES":"First CronJobicles",
	"Second Chronicles":"Second CronJobicles",
	"SECOND CHRONICLES":"Second CronJobicles",
	"Ezra":"Bot",
	"EZRA":"Bot",
	"Nehemiah":"JavaScript",
	"NEHEMIAH":"JavaScript",
	"Esther":"Shayla Nico",
	"ESTHER":"Shayla Nico",
	"Psalms":"Canaries",
	"PSALMS":"Canaries",
	"Proverbs":"Scripts",
	"PROVERBS":"Scripts",
	"proverbs":"scripts",
	"Ecclesiastes":"Script Kiddies",
	"ECCLESIASTES":"Script Kiddies",
	"Song of Solomon":"Audio Driver",
	"SONG OF SOLOMON":"Audio Driver",
	"Isaiah":"Mr. Robot",
	"ISAIAH":"Mr. Robot",
	"Jeremiah": "JavaRMIah",
	"JEREMIAH":"JavaRMIah",
	"Lamentations":"Detections",
	"LAMENTATIONS":"Detections",
	"Ezekiel":"McAfee",
	"EZEKIEL":"McAfee",
	"Daniel":"Symantec",
	"DANIEL":"Symantec",
	"Hosea":"Windows Defender",
	"HOSEA":"Windows Defender",
	"Joel":"Red Canary",
	"JOEL":"Windows Defender",
	"Amos":"bash",
	"AMOS":"bash",
	"Obadiah":"OWASP",
	"OBADIAH":"OWASP",
	"Jonah":"J'Pwnah",
	"JONAH":"J'Pwnah",
	"Micah":"Metasploit",
	"MICAH":"Metasploit",
	"Nahum":"Impersonation",
	"NAHUM":"Impersonation",
	"Habakkuk":"Impacket",
	"HABAKKUK":"Impacket",
	"Zephaniah":"Command Shell",
	"ZEPHANIAH":"Command Shell",
	"Haggai":"Hacker Eye",
	"HAGGAI":"Hacker Eye",
	"Zecheriah":"Zeke Proxy",
	"ZECHERIAH":"Zeke Proxy",
	"Malachi":"Malwareachi",
	"MALACHI":"Malwareachi",
	## New Testament
	"Matthew":"Emmanuel Goldstein",
	"MATTHEW":"Emmanuel Goldstein",
	"Mark":"",
	"MARK":"",
	"Luke":"",
	"LUKE":"",
	"John":"",
	"JOHN":"",
	"Acts ":"Penetration Testing ",
	"ACTS":"Penetration Testing",
	"Romans":"Trojans",
	"ROMANS":"Trojans",
	"First Corinithians":"First Credinthians",
	"FIRST CORINTHIANS":"First Credinthians",
	"2 Corinithians":"Second Credinthians",
	"2 CORINTHIANS":"Second Credinthians",
	"Galatians":"",
	"GALATIANS":"",
	"Ephesians":"",
	"EPHESIANS":"",
	"Philippians":"",
	"PHILIPPIANS":"",
	"Colossians":"",
	"COLOSSIANS":"",
	"First Thessalonians":"",
	"FIRST THESSALONIANS":"",
	"2 Thessalonians":"",
	"2 THESSALONIANS":"",
	"First Timothy":"First Mudge",
	"FIRST TIMOTHY":"First Mudge",
	"2 Timothy":"2 Mudge",
	"2 TIMOTHY":"2 Mudge",
	"Titus":"",
	"TITUS":"",
	"Philemon":"",
	"PHILEMON":"",
	"Hebrews":"",
	"HEBREWS":"",
	"James":"",
	"JAMES":"",
	"First Peter":"First MeterPeter",
	"FIRST PETER":"First MeterPeter",
	"2 Peter":"Second MeterPeter",
	"2 PETER":"Second MeterPeter",
	"Jude":"",
	"JUDE":"",
	"Revelation":"Redvelation",
	"REVELATION":"Redvelation",
	# The Lord
	"Lord God":"Great Code",
	"God": "Code",
	"GOD": "Code",
	"Lord": "Code",
	"LORD": "Code",
	"Jesus Christ": "Root",
	"Jesus": "Root",
	"JESUS": "Root",
	" Him ": " Root ",
	" He ": " Root ",
	"spirit": "Domain Administrator",
	# Prominent People
	"Adam ":"Zero Cool ",
	"Eve ":"Acid Burn ",
	"David": "Dade",
	"Pharaoh": "SysAdmin",
	"Priest":"Developer",
	"priest":"developer",
	"Pastor":"Scrum master",
	"pastor":"scrum master",
	"Prophet":"",
	"prophet":"",
	"soldier":"bot",
	"warrior":"bot",
	"army":"botnet",
	"armies":"botnets",
	"Soldier":"Bot",
	"Warrior":"Bot",
	"Army":"Botnet",
	"Armies":"Botnets",

#	"":
#	"Philistine":""
	"Woman":"User",
	"woman":"user",
	" man ":"user",
	" Man ":"user",
#	"Herod":"",
	"Nebuchadnezzar":"Phantom Phreak",
	"Babylonian":"Phreaker",	
	"Babylon":"Land of the Phreaks",
	" King":" Administrator",
	" king":" administrator",
	"Samuel":"Python",
	"Moses": "Elliot Alderson",
	"Lot": "Linus",
	"Jeremy": "JavaRMI",
	"Jacob": "Joey Pardella",
	"Judah": "Whiterose",
	"Isaac": "Lord Nikon",
	"Cain": "Eugene Belford",
	"Abel": "Hal",
	"Mary": "Angela Moss",
	"Gideon": "Gideon Coderd",
	"Timothy": "Mudge",
	# Apostles
	"John": "Mudge",
	"Simon": "HD Moore",
	"Peter": "MeterPeter",
	"James": "Jack Rhysider",
	"Andrew": "The Phantom Phreak",
	"Philip": "Crash Override",
# batholemew == Nathanael
	"Bartholemew": "Mudge",
	"Nathanael": "Mudge",
	"Thomas": "Razor",
	"Didymus": "Blade",
# Matthew == Levi
	"Matthew": "Emmanuel Goldstein",
	"Levi ": "Emmanuel Goldstein",
	"Thaddeus": "Mudge",
	"Judas Iscariot": "The Plague",
	"Judas": "The Plague",
	# Popular Expressions
	"let my people go":"free my system's memory",
	"let the people go":"free the system's memory",
	" amen ": " Hack The Planet ",
	" Amen ": " Hack The Planet ",
	# Prominent Places
	"the heaven":"the cloud",
	" Heaven ":" The Cloud ",
	" heaven ":" the cloud ",
	"city":"VLAN",
	"City":"VLAN",
	"House":"Server",
	"house":"server",
	" earth:": " network:",
	" earth ": " network ",
	"Earth ": "Network ",
	"Hell": "4chan",
	" river": " database",
	"robe": "hoodie",
	"robes": "hoodies",
	"righteous": "1337",
	"fish": "phish",
	"Fish": "Phish",
	"gate": "firewall",
	"border":"DMZ",
	"Jerusalem" : "Linux",
	"Egypt" : "evilcorp",
	"Israel" : "Active Directory",
	# Popular Adjectives
	"everlasting": "persistent",
	"eternal": "persistent",
	"holy":"1337",
	"Holy":"1337",
	"righteous":"1337",
	# Prominent Verbs
	"kill": "pwn",
	"killed": "pwned",
	"murder": "pwn",
	"murdered": "pwned",
	# Prominent Living Beings
	"beast": "blackhat",
	"beasts": "blackhats",
	"Satan":"Advanced Persistent Threat",
	# Popular nouns
	"god":"code",
	"gods":"codes",
	"plague":"virus",
	"flood":"SYN Flood",
	" ark ":" CyberArk ",
	"message":"payload",
	"life": "access",
	"cross": "Cross Site Scripting",
	"voices":"echoes",
	"voice":"echo",
	# Popular human nouns
	"Levites":"Software",
	"Fathers": "Parent processes",
	"Mothers": "Parent processes",
	"fathers": "parent processes",
	"mothers": "parent processes",
	"mother": "parent process",
	"Mother": "Parent process",
	"father": "parent process",
	"Father": "Parent process",
	"child ":"child process ",
	"children":"children processes",
	"firstborne":"first child process",
	"firstborn":"first child process",
	" son ":" child process ",
	"daughter":"child process",
	"murderer": "pwner",
	"killer": "pwner",
	"Gentile": "Hacker",
	"Gentiles": "Hackers",
	"gentile": "hacker",
	"gentiles": "hackers",
	"angel": "EDR",
	"Angel": "EDR",
	"angels": "EDRs",
	"Angels": "EDRs",
}

def update_verses(localPath):
	try:
		print("attempting to open verses.json")
		with open(localPath + 'bls_bible/static/verses.json', 'r') as file :
			filedata = file.read()
		print("verses.json opened")
	except Exception as e:
		print("Failed to open verses.json")
		print("Exception: ",e)
	for search_text, replace_text in verse_mapping.items():
		print("replacing text", search_text,"with",replace_text)
		filedata = filedata.replace(search_text, replace_text)
	print("writing now")
	with open(localPath + 'bls_bible/static/verses1.json', 'w') as file:
		file.write(filedata)
	print("text outputted")

def verse_of_the_day(localPath):
	random_verse = random.choice(open(localPath + 'bls_bible/static/verses1.json').readlines())
	return random_verse